"""empty message

Revision ID: e4e28a153aaf
Revises: 
Create Date: 2022-05-27 16:51:29.553109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e28a153aaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('venta_product', sa.Integer(), nullable=True))
    op.drop_constraint('ventas_username_id_fkey', 'ventas', type_='foreignkey')
    op.create_foreign_key(None, 'ventas', 'usuario', ['username_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventas', type_='foreignkey')
    op.create_foreign_key('ventas_username_id_fkey', 'ventas', 'usuario', ['username_id'], ['id'])
    op.drop_column('ventas', 'venta_product')
    # ### end Alembic commands ###
